import Foundation
import DevPlaceSwiftSDK

extension Profile {
    static var mock: Self {
        .init(
            user: .mock,
            posts: .mock,
            badges: .mock,
            badgeTotal: 0,
            badgeEarned: 0,
            projects: [
                .init(
                    id: "project-1",
                    slug: "devplace-ios",
                    userId: "user-1",
                    title: "DevPlace iOS",
                    description: "The native iOS client for DevPlace.",
                    projectType: "app",
                    status: "active",
                    stars: 42,
                    isPrivate: false,
                    readOnly: false,
                    releaseDate: nil,
                    demoDate: nil,
                    createdAt: Date(timeIntervalSince1970: 1_700_000_000),
                    updatedAt: nil,
                ),
                .init(
                    id: "project-2",
                    slug: "kree-request",
                    userId: "user-1",
                    title: "KreeRequest",
                    description: "A lightweight HTTP client wrapper.",
                    projectType: "library",
                    status: "active",
                    stars: 17,
                    isPrivate: false,
                    readOnly: false,
                    releaseDate: nil,
                    demoDate: nil,
                    createdAt: Date(timeIntervalSince1970: 1_700_000_000),
                    updatedAt: nil,
                ),
            ],
            gists: [],
            currentTab: "posts",
            postsCount: 5,
            isFollowing: false,
            isBlocked: false,
            isMuted: false,
            isOwner: true,
            canViewApiKey: true,
            apiKey: "mock-api-key",
            aiCorrectionEnabled: false,
            aiCorrectionSync: false,
            aiCorrectionPrompt: nil,
            aiModifierEnabled: false,
            aiModifierSync: false,
            aiModifierPrompt: nil,
            telegramPaired: false,
            notifTelegramPaired: false,
            canManageCustomization: true,
            custDisableGlobal: false,
            custDisablePagetype: false,
            rank: 1,
            followersCount: 0,
            followingCount: 0,
            viewerIsAdmin: false,
            media: [],
            xpProgressPercent: 42,
        )
    }
}
